[workspace]
authors = ["Ricardo Rios-Carrillo <rrioscar@uwo.ca>"]
channels = ["conda-forge"]
name = "axdki"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
dipy = ">=1.12.0,<2"
fury = ">=0.12.0,<0.13"
